const MovieData = [
    {
        id:1,
        img:"./images/firstMovie.jpg",
        date:"1994",
        director:"Frank Darabont",
        forAge:"13+",
        firstCharacterImg:"../images/CharacterImages/FirstMovie/firstCharacter.jpg",
        firstCharacterRealName:"Morgan Freeman",
        firstCharacterMovieName:"Ellis Boyd Redding",
        secondCharacterImg:"../images/CharacterImages/FirstMovie/secondCharacter.jpg",
        secondCharacterRealName:"Tim Robbins",
        secondCharacterMovieName:"Andy Dufresne",
        thirdCharacterImg:"../images/CharacterImages/FirstMovie/thirdCharacter.jpg",
        thirdCharacterRealName:"Clancy Brown",
        thirdCharacterMovieName:"Kaptan Hadley",
        fourthCharacterImg:"../images/CharacterImages/FirstMovie/fourthCharacter.jpg",
        fourthCharacterRealName:"Bob Gunton",
        fourthCharacterMovieName:"Manager Norton",
        fivethCharacterImg:"../images/CharacterImages/FirstMovie/fivethCharacter.jpg",
        fivethCharacterRealName:"William Sadler",
        fivethCharacterMovieName:"Heywood",
        sixthCharacterImg:"../images/CharacterImages/FirstMovie/sixthCharacter.jpg",
        sixthCharacterRealName:"Gill Bellows",
        sixthCharacterMovieName:"Tommy Williams",
        seventhCharacterImg:"../images/CharacterImages/FirstMovie/seventhCharacter.jpg",
        seventhCharacterRealName:"Mark Rolston",
        seventhCharacterMovieName:"Bogs Diamond",
        eighthCharacterImg:"../images/CharacterImages/FirstMovie/eighthCharacter.jpg",
        eighthCharacterRealName:"James Whitmore",
        eighthCharacterMovieName:"Brooks Hatlen",
        ninethCharacterImg:"../images/CharacterImages/FirstMovie/ninethCharacter.jpg",
        ninethCharacterRealName:"Brian Libby",
        ninethCharacterMovieName:"Floyd",
        tenthCharacterImg:"../images/CharacterImages/FirstMovie/tenthCharacter.jpg",
        tenthCharacterRealName:"Neil Giuntoli",
        tenthCharacterMovieName:"Jigger",
        eleventhCharacterImg:"../images/CharacterImages/FirstMovie/eleventhCharacter.jpg",
        eleventhCharacterRealName:"Larry Brandenburg",
        eleventhCharacterMovieName:"Skeet",
        liked:false,
        isInWatchList:false,
        title:"The Shawshank R...",
        time:"2h 22m",
        kind:["All","Drama"],
        score:"9.3",
        BgImage:"MovieScreenFirstMovie",
        summary:"Synopsis. In 1947, Andy Dufresne (Tim Robbins), a banker in Maine, is convicted of murdering his wife and her lover, a golf pro. Since the state of Maine has no death penalty, he is given two consecutive life sentences and sent to the notoriously harsh Shawshank Prison."
        
    },
    {
        id:2,
        img:"./images/secondMovie.jpg",
        date:"1972",
        director:"Francis Ford Coppola",
        forAge:"18+",
        firstCharacterImg:"../images/CharacterImages/SecondMovie/firstCharacter.jpg",
        firstCharacterRealName:"Marlon Brando",
        firstCharacterMovieName:"Vito Corleone",
        secondCharacterImg:"../images/CharacterImages/SecondMovie/secondCharacter.jpg",
        secondCharacterRealName:"Al Pacino",
        secondCharacterMovieName:"Michael Corleone",
        thirdCharacterImg:"../images/CharacterImages/SecondMovie/thirdCharacter.jpg",
        thirdCharacterRealName:"Morgana King",
        thirdCharacterMovieName:"Carmela Corleone",
        fourthCharacterImg:"../images/CharacterImages/SecondMovie/fourthCharacter.jpg",
        fourthCharacterRealName:"James Caan",
        fourthCharacterMovieName:"Santino Corleone",
        fivethCharacterImg:"../images/CharacterImages/SecondMovie/fivethCharacter.jpg",
        fivethCharacterRealName:"Diane Keaton",
        fivethCharacterMovieName:"Kay Adams",
        sixthCharacterImg:"../images/CharacterImages/SecondMovie/sixthCharacter.jpg",
        sixthCharacterRealName:"Talia Shire",
        sixthCharacterMovieName:"Connie Corleone",
        seventhCharacterImg:"../images/CharacterImages/SecondMovie/seventhCharacter.jpg",
        seventhCharacterRealName:"John Cazale",
        seventhCharacterMovieName:"Fredo Corleone",
        eighthCharacterImg:"../images/CharacterImages/SecondMovie/eighthCharacter.jpg",
        eighthCharacterRealName:"Gianni Russo",
        eighthCharacterMovieName:"Carlo Rizzi",
        ninethCharacterImg:"../images/CharacterImages/SecondMovie/ninethCharacter.png",
        ninethCharacterRealName:"Simonetta Stefanelli",
        ninethCharacterMovieName:"Apollonia Corleone",
        tenthCharacterImg:"../images/CharacterImages/SecondMovie/tenthCharacter.jpg",
        tenthCharacterRealName:"Al Lettieri",
        tenthCharacterMovieName:"Virgil Sollozzo",
        eleventhCharacterImg:"../images/CharacterImages/SecondMovie/eleventhCharacter.jpg",
        eleventhCharacterRealName:"Julie Gregg",
        eleventhCharacterMovieName:"Sandra Corleone",
        liked:false,
        isInWatchList:false,
        title:"The Godfather",
        time:"2h 55m",
        kind:["All","Crime","Drama"],
        score:"9.2",
        BgImage:"MovieScreenSecondMovie",
        summary:"The Godfather is a classic novel that tells the story of the powerful Italian-American crime family, the Corleones. Filled with themes of loyalty, betrayal, and power, the book delves into the world of organized crime and the complex relationships within the family."
    },
    {
        id:3,
        img:"./images/thirdMovie.jpg",
        date:"2008",
        director:"Christopher Nolan",
        forAge:"16+",
        firstCharacterImg:"../images/CharacterImages/ThirdMovie/firstCharacter.jpg",
        firstCharacterRealName:"Christian Bale",
        firstCharacterMovieName:"Bruce Wayne",
        secondCharacterImg:"../images/CharacterImages/ThirdMovie/secondCharacter.jpg",
        secondCharacterRealName:"Heath Ledger",
        secondCharacterMovieName:"Joker",
        thirdCharacterImg:"../images/CharacterImages/ThirdMovie/thirdCharacter.jpg",
        thirdCharacterRealName:"Gary Oldman",
        thirdCharacterMovieName:"James Gordon",
        liked:false,
        isInWatchList:false,
        title:"The Dark Knight",
        time:"2h 32m",
        kind:["All","Action","Crime","Drama"],
        score:"9.0",
        BgImage:"MovieScreenThirdMovie",
        summary:"The plot follows the vigilante Batman, police lieutenant James Gordon, and district attorney Harvey Dent, who form an alliance to dismantle organized crime in Gotham City. Their efforts are derailed by the Joker, an anarchistic mastermind who seeks to test how far Batman will go to save the city from chaos."
    },
    {
        id:4,
        img:"./images/fourthMovie.jpg",
        date:"1974",
        director:"Francis Ford Coppola",
        forAge:"18+",
        firstCharacterImg:"../images/CharacterImages/FourthMovie/firstCharacter.jpg",
        firstCharacterRealName:"Robert De Niro",
        firstCharacterMovieName:"Vito Corleone",
        secondCharacterImg:"../images/CharacterImages/SecondMovie/secondCharacter.jpg",
        secondCharacterRealName:"Al Pacino",
        secondCharacterMovieName:"Michael Corleone",
        thirdCharacterImg:"../images/CharacterImages/FourthMovie/thirdCharacter.jpg",
        thirdCharacterRealName:"Diane Kiaten",
        thirdCharacterMovieName:"Kay Adams",
        liked:false,
        isInWatchList:false,
        title:"The Godfather Part II",
        time:"3h 22m",
        kind:["All","Crime","Drama"],
        score:"9.0",
        BgImage:"MovieScreenFourthMovie",
        summary:"The continuing saga of the Corleone crime family tells the story of a young Vito Corleone growing up in Sicily and in 1910s New York; and follows Michael Corleone in the 1950s as he attempts to expand the family business into Las Vegas, Hollywood and Cuba."
    },
    {
        id:5,
        img:"./images/fivethMovie.jpg",
        date:"1957",
        director:"Sidney Lumet",
        forAge:"15+",
        firstCharacterImg:"../images/CharacterImages/FivethMovie/firstCharacter.jpg",
        firstCharacterRealName:"Henry Fonda",
        firstCharacterMovieName:"Juror Davis",
        secondCharacterImg:"../images/CharacterImages/FivethMovie/secondCharacter.jpg",
        secondCharacterRealName:"Ed Begley",
        secondCharacterMovieName:"Juror #10",
        thirdCharacterImg:"../images/CharacterImages/FivethMovie/thirdCharacter.jpg",
        thirdCharacterRealName:"Jack Klugman",
        thirdCharacterMovieName:"Juror #5",
        liked:false,
        isInWatchList:false,
        title:"12 Angry Men",
        time:"1h 36m",
        kind:["All","Crime","Drama"],
        score:"9.0",
        BgImage:"MovieScreenFivethMovie",
        summary:"With a cast of fourteen characters and set almost entirely inside one room, 12 Angry Men tells the story of a jury deliberating a murder trial during a hot New York afternoon. It explores the motivations and prejudices of individual jury members and how they eventually argue their way to a unanimous decision."
    },
    {
        id:6,
        img:"./images/sixthMovie.jpg",
        date:"1993",
        director:"Steven Spielberg",
        forAge:"18+",
        firstCharacterImg:"../images/CharacterImages/SixthMovie/firstCharacter.jpg",
        firstCharacterRealName:"Liam Neeson",
        firstCharacterMovieName:"Oskar Schindler",
        secondCharacterImg:"../images/CharacterImages/SixthMovie/secondCharacter.jpg",
        secondCharacterRealName:"Ralph Fiennes",
        secondCharacterMovieName:"Amon Göth",
        thirdCharacterImg:"../images/CharacterImages/SixthMovie/thirdCharacter.jpg",
        thirdCharacterRealName:"Embeth Davidtz",
        thirdCharacterMovieName:"Helen Hirsch",
        liked:false,
        isInWatchList:false,
        title:"Schindler's List",
        time:"3h 15m",
        kind:["All","Biography","Drama","History"],
        score:"9.0",
        BgImage:"MovieScreenSixthMovie",
        summary:"Schindler's List by Thomas Keneally was published in 1982. The plot revolves around Oskar Schindler's attempt to rescue over 1100 Jews from Nazi concentration camps. Schindler, a factory owner, and his wife, Emilie, hire Itzhak Stern as their accountant."
    },
    {
        id:7,
        img:"./images/seventhMovie.jpg",
        date:"2003",
        director:"Peter Jackson",
        forAge:"16+",
        firstCharacterImg:"../images/CharacterImages/SeventhMovie/firstCharacter.jpg",
        firstCharacterRealName:"Elijah Wood",
        firstCharacterMovieName:"Frodo Baggins",
        secondCharacterImg:"../images/CharacterImages/SeventhMovie/secondCharacter.jpg",
        secondCharacterRealName:"Ian McKellen",
        secondCharacterMovieName:"Gandalf",
        thirdCharacterImg:"../images/CharacterImages/SeventhMovie/thirdCharacter.jpg",
        thirdCharacterRealName:"Miranda Otto",
        thirdCharacterMovieName:"Éowyn",
        liked:false,
        isInWatchList:false,
        title:"The Lord of the...",
        time:"3h 21m",
        kind:["All","Action","Adventure","Drama"],
        score:"9.0",
        BgImage:"MovieScreenSeventhMovie",
        summary:"The final confrontation between the forces of good and evil fighting for control of the future of Middle-earth. Frodo and Sam reach Mordor in their quest to destroy the One Ring, while Aragorn leads the forces of good against Sauron's evil army at the stone city of Minas Tirith."
    },
    {
        id:8,
        img:"./images/eighthMovie.jpg",
        date:"1994",
        director:"Quentin Tarantino",
        forAge:"18+",
        firstCharacterImg:"../images/CharacterImages/EighthMovie/firstCharacter.jpg",
        firstCharacterRealName:"John Travolta",
        firstCharacterMovieName:"Vincent Vega",
        secondCharacterImg:"../images/CharacterImages/EighthMovie/secondCharacter.jpg",
        secondCharacterRealName:"Samuel L. Jackson",
        secondCharacterMovieName:"Jules Winnfield",
        thirdCharacterImg:"../images/CharacterImages/EighthMovie/thirdCharacter.jpg",
        thirdCharacterRealName:"Uma Thurman",
        thirdCharacterMovieName:"Mia Wallace",
        liked:false,
        isInWatchList:false,
        title:"Pulp Fiction",
        time:"2h 34m",
        kind:["All","Crime","Drama"],
        score:"8.9",
        BgImage:"MovieScreenEighthMovie",
        summary:"The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption."
    },
    {
        id:9,
        img:"./images/ninethMovie.jpg",
        date:"2001",
        director:"Peter Jackson",
        forAge:"13+",
        firstCharacterImg:"../images/CharacterImages/SeventhMovie/firstCharacter.jpg",
        firstCharacterRealName:"Elijah Wood",
        firstCharacterMovieName:"Frodo Baggins",
        secondCharacterImg:"../images/CharacterImages/SeventhMovie/secondCharacter.jpg",
        secondCharacterRealName:"Ian McKellen",
        secondCharacterMovieName:"Gandalf",
        thirdCharacterImg:"../images/CharacterImages/NinethMovie/thirdCharacter.jpg",
        thirdCharacterRealName:"Cate Blanchett",
        thirdCharacterMovieName:"Galadriel",
        liked:false,
        isInWatchList:false,
        title:"The Lord of the...",
        time:"2h 58m",
        kind:["All","Action","Adventure","Drama"],
        score:"8.9",
        BgImage:"MovieScreenNinethMovie",
        summary:"The Ring has found its way to the young hobbit Frodo Baggins. The fate of Middle-earth hangs in the balance as Frodo and eight companions (who form the Fellowship of the Ring) begin their perilous journey to Mount Doom in the land of Mordor, the only place where the Ring can be destroyed."
    },
    {
        id:10,
        img:"./images/tenthMovie.jpg",
        date:"2024",
        director:"Denis Villeneuve",
        forAge:"13+",
        firstCharacterImg:"../images/CharacterImages/TenthMovie/firstCharacter.jpg",
        firstCharacterRealName:"Austin Butler",
        firstCharacterMovieName:"Feyd-Rautha",
        secondCharacterImg:"../images/CharacterImages/TenthMovie/secondCharacter.png",
        secondCharacterRealName:"Timothée Chalamet",
        secondCharacterMovieName:"Paul Atreides",
        thirdCharacterImg:"../images/CharacterImages/TenthMovie/thirdCharacter.jpg",
        thirdCharacterRealName:"Zendaya",
        thirdCharacterMovieName:"Chani",
        liked:false,
        isInWatchList:false,
        title:"Dune: Part Two",
        time:"2h 46m",
        kind:["All","Action","Adventure","Drama"],
        score:"8.9",
        BgImage:"MovieScreenTenthMovie",
        summary:"Paul Atreides unites with Chani and the Fremen while on a warpath of revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the known universe, he endeavors to prevent a terrible future only he can foresee."
    },
    
]

export default MovieData